# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/fgk/Developer/tribune

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/fgk/Developer/tribune

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fgk/Developer/tribune/CMakeFiles /Users/fgk/Developer/tribune//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fgk/Developer/tribune/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tribune_lib

# Build rule for target.
tribune_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tribune_lib
.PHONY : tribune_lib

# fast build rule for target.
tribune_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/build
.PHONY : tribune_lib/fast

#=============================================================================
# Target rules for targets named tribune_test_build

# Build rule for target.
tribune_test_build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tribune_test_build
.PHONY : tribune_test_build

# fast build rule for target.
tribune_test_build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_test_build.dir/build.make CMakeFiles/tribune_test_build.dir/build
.PHONY : tribune_test_build/fast

examples/test_build.o: examples/test_build.cpp.o
.PHONY : examples/test_build.o

# target to build an object file
examples/test_build.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_test_build.dir/build.make CMakeFiles/tribune_test_build.dir/examples/test_build.cpp.o
.PHONY : examples/test_build.cpp.o

examples/test_build.i: examples/test_build.cpp.i
.PHONY : examples/test_build.i

# target to preprocess a source file
examples/test_build.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_test_build.dir/build.make CMakeFiles/tribune_test_build.dir/examples/test_build.cpp.i
.PHONY : examples/test_build.cpp.i

examples/test_build.s: examples/test_build.cpp.s
.PHONY : examples/test_build.s

# target to generate assembly for a file
examples/test_build.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_test_build.dir/build.make CMakeFiles/tribune_test_build.dir/examples/test_build.cpp.s
.PHONY : examples/test_build.cpp.s

src/client/tribune_client.o: src/client/tribune_client.cpp.o
.PHONY : src/client/tribune_client.o

# target to build an object file
src/client/tribune_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/client/tribune_client.cpp.o
.PHONY : src/client/tribune_client.cpp.o

src/client/tribune_client.i: src/client/tribune_client.cpp.i
.PHONY : src/client/tribune_client.i

# target to preprocess a source file
src/client/tribune_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/client/tribune_client.cpp.i
.PHONY : src/client/tribune_client.cpp.i

src/client/tribune_client.s: src/client/tribune_client.cpp.s
.PHONY : src/client/tribune_client.s

# target to generate assembly for a file
src/client/tribune_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/client/tribune_client.cpp.s
.PHONY : src/client/tribune_client.cpp.s

src/crypto/signature.o: src/crypto/signature.cpp.o
.PHONY : src/crypto/signature.o

# target to build an object file
src/crypto/signature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/crypto/signature.cpp.o
.PHONY : src/crypto/signature.cpp.o

src/crypto/signature.i: src/crypto/signature.cpp.i
.PHONY : src/crypto/signature.i

# target to preprocess a source file
src/crypto/signature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/crypto/signature.cpp.i
.PHONY : src/crypto/signature.cpp.i

src/crypto/signature.s: src/crypto/signature.cpp.s
.PHONY : src/crypto/signature.s

# target to generate assembly for a file
src/crypto/signature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/crypto/signature.cpp.s
.PHONY : src/crypto/signature.cpp.s

src/mpc/sum_computation.o: src/mpc/sum_computation.cpp.o
.PHONY : src/mpc/sum_computation.o

# target to build an object file
src/mpc/sum_computation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/mpc/sum_computation.cpp.o
.PHONY : src/mpc/sum_computation.cpp.o

src/mpc/sum_computation.i: src/mpc/sum_computation.cpp.i
.PHONY : src/mpc/sum_computation.i

# target to preprocess a source file
src/mpc/sum_computation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/mpc/sum_computation.cpp.i
.PHONY : src/mpc/sum_computation.cpp.i

src/mpc/sum_computation.s: src/mpc/sum_computation.cpp.s
.PHONY : src/mpc/sum_computation.s

# target to generate assembly for a file
src/mpc/sum_computation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/mpc/sum_computation.cpp.s
.PHONY : src/mpc/sum_computation.cpp.s

src/protocol/parser.o: src/protocol/parser.cpp.o
.PHONY : src/protocol/parser.o

# target to build an object file
src/protocol/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/protocol/parser.cpp.o
.PHONY : src/protocol/parser.cpp.o

src/protocol/parser.i: src/protocol/parser.cpp.i
.PHONY : src/protocol/parser.i

# target to preprocess a source file
src/protocol/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/protocol/parser.cpp.i
.PHONY : src/protocol/parser.cpp.i

src/protocol/parser.s: src/protocol/parser.cpp.s
.PHONY : src/protocol/parser.s

# target to generate assembly for a file
src/protocol/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/protocol/parser.cpp.s
.PHONY : src/protocol/parser.cpp.s

src/server/client_state.o: src/server/client_state.cpp.o
.PHONY : src/server/client_state.o

# target to build an object file
src/server/client_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/server/client_state.cpp.o
.PHONY : src/server/client_state.cpp.o

src/server/client_state.i: src/server/client_state.cpp.i
.PHONY : src/server/client_state.i

# target to preprocess a source file
src/server/client_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/server/client_state.cpp.i
.PHONY : src/server/client_state.cpp.i

src/server/client_state.s: src/server/client_state.cpp.s
.PHONY : src/server/client_state.s

# target to generate assembly for a file
src/server/client_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/server/client_state.cpp.s
.PHONY : src/server/client_state.cpp.s

src/server/tribune_server.o: src/server/tribune_server.cpp.o
.PHONY : src/server/tribune_server.o

# target to build an object file
src/server/tribune_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/server/tribune_server.cpp.o
.PHONY : src/server/tribune_server.cpp.o

src/server/tribune_server.i: src/server/tribune_server.cpp.i
.PHONY : src/server/tribune_server.i

# target to preprocess a source file
src/server/tribune_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/server/tribune_server.cpp.i
.PHONY : src/server/tribune_server.cpp.i

src/server/tribune_server.s: src/server/tribune_server.cpp.s
.PHONY : src/server/tribune_server.s

# target to generate assembly for a file
src/server/tribune_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tribune_lib.dir/build.make CMakeFiles/tribune_lib.dir/src/server/tribune_server.cpp.s
.PHONY : src/server/tribune_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tribune_lib"
	@echo "... tribune_test_build"
	@echo "... examples/test_build.o"
	@echo "... examples/test_build.i"
	@echo "... examples/test_build.s"
	@echo "... src/client/tribune_client.o"
	@echo "... src/client/tribune_client.i"
	@echo "... src/client/tribune_client.s"
	@echo "... src/crypto/signature.o"
	@echo "... src/crypto/signature.i"
	@echo "... src/crypto/signature.s"
	@echo "... src/mpc/sum_computation.o"
	@echo "... src/mpc/sum_computation.i"
	@echo "... src/mpc/sum_computation.s"
	@echo "... src/protocol/parser.o"
	@echo "... src/protocol/parser.i"
	@echo "... src/protocol/parser.s"
	@echo "... src/server/client_state.o"
	@echo "... src/server/client_state.i"
	@echo "... src/server/client_state.s"
	@echo "... src/server/tribune_server.o"
	@echo "... src/server/tribune_server.i"
	@echo "... src/server/tribune_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

